#include "pinfmt.h"

void Pinfmt_AllOpen()
{
    PinHandle hPin=UTL_GetPinHandle();
    UTL_SetPinOpen(hPin, UT_ON);
    UTL_SendPin(hPin,"ALLPIN");
    UTL_DeleteHandle(hPin);
}
void Pinfmt_AllHigh()
{

}
void Pinfmt_AllLow()
{/*
    PinHandle hPin=UTL_GetPinHandle();
    UTL_InitializePinHandle(hPin);
                                 //set target vi number that should be used
                                 //set FIXL waveform
    //UTL_SendPin(hPin,     );   //send above setting to ¨ALLPIN¨ 
    UTL_DeleteHandle(hPin);
*/
}

void PFUNC(double wl, double rl)
//	+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+
//	| CMD  | DES  |ACT1-1|ACT1-2|ACT2-1|ACT2-2|WR 1-1|WR 1-2|MWR1-1|MWR1-2|RD 1-1|RD 1-2|PRE1-1|PRE1-2|REF1-1|REF1-2|CAS2-1|CAS2-2|MRW1-1|MRW1-2|MRW2-1|MRW2-2|MRR1-1|MRR1-2|MPC -1|MPC -2| SRE-1| SRE-2| SRX-1| SRX-2|
//	+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+
//	| CS   | Low  | High | Low  | High | Low  | High | Low  | High | Low  | High | Low  | High | Low  | High | Low  | High | Low  | High | Low  | High | Low  | High | Low  | High | Low  | High | Low  | High | Low  |
//	+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+
//	| CA0  | ---  | High | BA0  | High | ROW0 | Low  | BA0  | Low  | BA0  | Low  | BA0  | Low  | BA0  | Low  | BA0  | Low  | COL2 | Low  | MA0  | Low  | OP0  | Low  | MA0  | Low  | OP0  | Low  | ---  | Low  | ---  |
//	| CA1  | ---  | Low  | BA1  | High | ROW1 | Low  | BA1  | Low  | BA1  | High | BA1  | Low  | BA1  | Low  | BA1  | High | COL3 | High | MA1  | High | OP1  | High | MA1  | Low  | OP1  | Low  | ---  | Low  | ---  |
//	| CA2  | ---  | ROW12| BA2  | ROW6 | ROW2 | High | BA2  | High | BA2  | Low  | BA2  | Low  | BA2  | Low  | BA2  | Low  | COL4 | High | MA2  | High | OP2  | High | MA2  | Low  | OP2  | Low  | ---  | High | ---  |
//	| CA3  | ---  | ROW13| ---  | ROW7 | ROW3 | Low  | Low  | High | Low  | Low  | Low  | Low  | ---  | High | ---  | Low  | COL5 | Low  | MA3  | Low  | OP3  | High | MA3  | Low  | OP3  | High | ---  | Low  | ---  |
//	| CA4  | ---  | ROW14| ROW10| ROW8 | ROW4 | Low  | COL9 | Low  | COL9 | Low  | COL9 | High | ---  | Low  | ---  | High | COL6 | Low  | MA4  | High | OP4  | Low  | MA4  | Low  | OP4  | High | ---  | High | ---  | MR0-MR5...Y0-Y5 MR0-MR5...Y0-Y5
//	| CA5  | ---  | ROW15| ROW11| ROW9 | ROW5 | BL   | AP   | Low  | AP   | BL   | AP   | AB   | ---  | AB   | ---  | COL8 | COL7 | OP7  | MA5  | OP6  | OP5  | ---  | MA5  | OP6  | OP5  | ---  | ---  | ---  | ---  | OP0-OP7...X0-X7 OP0-OP7...X0-X7
//	+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+
//	| CYP  | CYP1 | CYP2 | CYP3 | CYP5 | CYP6 | CYP7 | CYP8 | CYP7 | CYP8 | CYP7 | CYP8 | CYP7 | CYP8 | CYP7 | CYP8 | CYP10| CYP11| CYP12| CYP13| CYP14| CYP15| CYP12| CYP13| CYP14| CYP15| CYP7 | CYP1 | CYP7 | CYP1 |
//	|      |      |      | CYP4 |      |      |      | CYP9 |      | CYP9 |      | CYP9 |      | CYP9 |      | CYP9 |      |      |      |      |      |      |      |      |      |      |      |      |      |      |
//	+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+
{
        wl = wl + 4;
        rl = rl + 3;
//	                                                   +------------+------------+------------+------------+------------+------------+------------+------------+------------+------------+--------------+-------------+-------------+-------------+-------------+
//                                                         |  CYP1      | CYP2       | CYP3       | CYP4       | CYP5       | CYP6       | CYP7       | CYP8       | CYP9       | CYP10      | CYP11        | CYP12       | CYP13       | CYP14       |CYP15        |
//	                                                   +------------+------------+------------+------------+------------+------------+------------+------------+------------+------------+--------------+-------------+-------------+-------------+-------------+
//                                                         |  DES       | ACT1-1     |ACT1-2      | ACT1-2     | ACT2-1     | ACT2-2     | WR1-1      | WR1-2      | WR1-2      |CAS2-1      |CAS2-2        | MRW1-1      | MRW1-2      | MRW2-1      |MRW2-2       |
//                                                         |            |            |            |            |            |            | RD1-1      | RD1-2      | RD1-2      |            |              | MRR1-1      | MRR1-2      | MPC-1       |MPC-2        |
//                                                         |            |            |            |            |            |            | PRE1-1     | PRE1-2     | PRE1-2     |            |              |             |             |             |             |
//                                                         |            |            |            |            |            |            | REF1-1     | REF1-2     | REF1-2     |            |              |             |             |             |             |
//                                                         |            |            |            |            |            |            | MWR1-1     | MWR1-2     | MWR1-2     |            |              |             |             |             |             |
//                                                         | SRE-2      |            |            |            |            |            | SRE-1      |            |            |            |              |             |             |             |             |
//                                                         | SRX-2      |            |            |            |            |            | SRX-1      |            |            |            |              |             |             |             |             |
//	                                                   +------------+------------+------------+------------+------------+------------+------------+------------+------------+------------+--------------+-------------+-------------+-------------+-------------+
/*
    P("CK_t" ,P_IN(1),P_RZZ  ,P_BCLK( 1),P_CCLK( 1),PDSA(1,P_C(29)),PDSA(2,P_C(29)),PDSA(3,P_C(29)),PDSA(4,P_C(29)),PDSA(5,P_C(29)), PDSA(6,P_C(29)),PDSA(7,P_C(29)),PDSA(8,P_C(29)),PDSA(9,P_C(29)),PDSA(10,P_C(29)),PDSA(11,P_C(29)),PDSA(12,P_C(29)),PDSA(13,P_C(29)),PDSA(14,P_C(29)),PDSA(15,P_C(29)));
    P("CK_c" ,P_IN(1),P_IRZZ ,P_BCLK( 1),P_CCLK( 1),PDSA(1,P_C(29)),PDSA(2,P_C(29)),PDSA(3,P_C(29)),PDSA(4,P_C(29)),PDSA(5,P_C(29)), PDSA(6,P_C(29)),PDSA(7,P_C(29)),PDSA(8,P_C(29)),PDSA(9,P_C(29)),PDSA(10,P_C(29)),PDSA(11,P_C(29)),PDSA(12,P_C(29)),PDSA(13,P_C(29)),PDSA(14,P_C(29)),PDSA(15,P_C(29))); 
    P("CKE"  ,P_IN( ),P_     ,P_BCLK(  ),P_CCLK(  ),PDSA(1,P_C(14)),PDSA(2,P_C(14)),PDSA(3,P_C(14)),PDSA(4,P_C(14)),PDSA(5,P_C(14)), PDSA(6,P_C(14)),PDSA(7,P_C(14)),PDSA(8,P_C(14)),PDSA(9,P_C(14)),PDSA(10,P_C(14)),PDSA(11,P_C(14)),PDSA(12,P_C(14)),PDSA(13,P_C(14)),PDSA(14,P_C(14)),PDSA(15,P_C(14)));
    P("ODTCA",P_IN( ),P_     ,P_BCLK(  ),P_CCLK(  ),PDSA(1,P_C( 3)),PDSA(2,P_C( 3)),PDSA(3,P_C( 3)),PDSA(4,P_C( 3)),PDSA(5,P_C( 3)), PDSA(6,P_C( 3)),PDSA(7,P_C( 3)),PDSA(8,P_C( 3)),PDSA(9,P_C( 3)),PDSA(10,P_C( 3)),PDSA(11,P_C( 3)),PDSA(12,P_C( 3)),PDSA(13,P_C( 3)),PDSA(14,P_C( 3)),PDSA(15,P_C( 3)));
    P("RST_n",P_IN( ),P_     ,P_BCLK(  ),P_CCLK(  ),PDSA(1,P_C(13)),PDSA(2,P_C(13)),PDSA(3,P_C(13)),PDSA(4,P_C(13)),PDSA(5,P_C(13)), PDSA(6,P_C(13)),PDSA(7,P_C(13)),PDSA(8,P_C(13)),PDSA(9,P_C(13)),PDSA(10,P_C(13)),PDSA(11,P_C(13)),PDSA(12,P_C(13)),PDSA(13,P_C(13)),PDSA(14,P_C(13)),PDSA(15,P_C(13)));
    P("CS"   ,P_IN( ),P_     ,P_BCLK(  ),P_CCLK(  ),PDSA(1,P_FL)   ,PDSA(2,P_C(10)),PDSA(3,P_FL)   ,PDSA(4,P_FL)   ,PDSA(5,P_C(10)), PDSA(6,P_FL)   ,PDSA(7,P_C(10)),PDSA(8,P_FL)   ,PDSA(9,P_FL)   ,PDSA(10,P_C(10)),PDSA(11,P_FL)   ,PDSA(12,P_C(10)),PDSA(13,P_FL)   ,PDSA(14,P_C(10)),PDSA(15,P_FL)   );
    P("CA0"  ,P_IN( ),P_     ,P_BCLK(  ),P_CCLK(  ),PDSA(1,P_FL)   ,PDSA(2,P_C( 4)),PDSA(3,P_C(17)),PDSA(4,P_X(17)),PDSA(5,P_C( 4)), PDSA(6,P_X( 0)),PDSA(7,P_C( 4)),PDSA(8,P_C(17)),PDSA(9,P_Y(17)),PDSA(10,P_C( 4)),PDSA(11,P_FL)   ,PDSA(12,P_C( 4)),PDSA(13,P_X( 0)),PDSA(14,P_C( 4)),PDSA(15,P_Y( 0)));
    P("CA1"  ,P_IN( ),P_     ,P_BCLK(  ),P_CCLK(  ),PDSA(1,P_FL)   ,PDSA(2,P_C( 5)),PDSA(3,P_C(18)),PDSA(4,P_X(18)),PDSA(5,P_C( 5)), PDSA(6,P_X( 1)),PDSA(7,P_C( 5)),PDSA(8,P_C(18)),PDSA(9,P_Y(18)),PDSA(10,P_C( 5)),PDSA(11,P_Y( 3)),PDSA(12,P_C( 5)),PDSA(13,P_X( 1)),PDSA(14,P_C( 5)),PDSA(15,P_Y( 1)));
    P("CA2"  ,P_IN( ),P_     ,P_BCLK(  ),P_CCLK(  ),PDSA(1,P_FL)   ,PDSA(2,P_X(12)),PDSA(3,P_C(19)),PDSA(4,P_X(19)),PDSA(5,P_X( 6)), PDSA(6,P_X( 2)),PDSA(7,P_C( 6)),PDSA(8,P_C(19)),PDSA(9,P_Y(19)),PDSA(10,P_C( 6)),PDSA(11,P_Y( 4)),PDSA(12,P_C( 6)),PDSA(13,P_X( 2)),PDSA(14,P_C( 6)),PDSA(15,P_Y( 2)));
    P("CA3"  ,P_IN( ),P_     ,P_BCLK(  ),P_CCLK(  ),PDSA(1,P_FL)   ,PDSA(2,P_X(13)),PDSA(3,P_FL)   ,PDSA(4,P_FL)   ,PDSA(5,P_X( 7)), PDSA(6,P_X( 3)),PDSA(7,P_C( 7)),PDSA(8,P_FL)   ,PDSA(9,P_FL)   ,PDSA(10,P_C( 7)),PDSA(11,P_Y( 5)),PDSA(12,P_C( 7)),PDSA(13,P_X( 3)),PDSA(14,P_C( 7)),PDSA(15,P_Y( 3)));
    P("CA4"  ,P_IN( ),P_     ,P_BCLK(  ),P_CCLK(  ),PDSA(1,P_FL)   ,PDSA(2,P_X(14)),PDSA(3,P_X(10)),PDSA(4,P_X(10)),PDSA(5,P_X( 8)), PDSA(6,P_X( 4)),PDSA(7,P_C( 8)),PDSA(8,P_Y( 9)),PDSA(9,P_Y( 9)),PDSA(10,P_C( 8)),PDSA(11,P_Y( 6)),PDSA(12,P_C( 8)),PDSA(13,P_X( 4)),PDSA(14,P_C( 8)),PDSA(15,P_Y( 4)));
    P("CA5"  ,P_IN( ),P_     ,P_BCLK(  ),P_CCLK(  ),PDSA(1,P_FL)   ,PDSA(2,P_X(15)),PDSA(3,P_X(11)),PDSA(4,P_X(11)),PDSA(5,P_X( 9)), PDSA(6,P_X( 5)),PDSA(7,P_C( 9)),PDSA(8,P_C( 9)),PDSA(9,P_C( 9)),PDSA(10,P_Y( 8)),PDSA(11,P_Y( 7)),PDSA(12,P_Y( 7)),PDSA(13,P_X( 5)),PDSA(14,P_Y( 6)),PDSA(15,P_Y( 5)));
    P("DQ0"  ,P_IN( ),P_     ,P_BCLK(  ),P_CCLK(  ),P_DRE(1),P_DRENRZ,P_DRECLK(1),P_IOC,P_OUTL(1),P_VT(1),P_DRCYCDLY(wl),P_EXPCYCDLY(rl),P_STRB(1,1),P_EXPA(1), P_STRB(2,1),P_EXPB(2),PDSA(1,P_D( 0)),PDSB(1,P_SD( 0)),PDSA(2,P_D( 0)),PDSB(2,P_SD( 0)),PDSA(3,P_D( 0)),PDSB(3,P_SD( 0)),PDSA(4,P_D( 0)),PDSB(4,P_SD( 0)),PDSA(5,P_D( 0)),PDSB(5,P_SD( 0)),PDSA(6,P_D( 0)),PDSB(6,P_SD( 0)),PDSA(7,P_D( 0)),PDSB(7,P_SD( 0)),PDSA(8,P_D( 0)),PDSB(8,P_SD( 0)),PDSA(9,P_D( 0)),PDSB(9,P_SD( 0)),PDSA(10,P_D( 0)),PDSB(10,P_SD( 0)),PDSA(11,P_D( 0)),PDSB(11,P_SD( 0)),PDSA(12,P_D( 0)),PDSB(12,P_SD( 0)),PDSA(13,P_D( 0)),PDSB(13,P_SD( 0)),PDSA(14,P_D( 0)),PDSB(14,P_SD( 0)),PDSA(15,P_D( 0)),PDSB(15,P_SD( 0)));
    P("DQ1"  ,P_IN( ),P_     ,P_BCLK(  ),P_CCLK(  ),P_DRE( ),P_DRENRZ,P_DRECLK( ),P_IOC,P_OUTL( ),P_VT( ),P_DRCYCDLY(wl),P_EXPCYCDLY(rl),P_STRB( , ),P_EXPA(1), P_STRB( , ),P_EXPB(2),PDSA(1,P_D( 1)),PDSB(1,P_SD( 1)),PDSA(2,P_D( 1)),PDSB(2,P_SD( 1)),PDSA(3,P_D( 1)),PDSB(3,P_SD( 1)),PDSA(4,P_D( 1)),PDSB(4,P_SD( 1)),PDSA(5,P_D( 1)),PDSB(5,P_SD( 1)),PDSA(6,P_D( 1)),PDSB(6,P_SD( 1)),PDSA(7,P_D( 1)),PDSB(7,P_SD( 1)),PDSA(8,P_D( 1)),PDSB(8,P_SD( 1)),PDSA(9,P_D( 1)),PDSB(9,P_SD( 1)),PDSA(10,P_D( 1)),PDSB(10,P_SD( 1)),PDSA(11,P_D( 1)),PDSB(11,P_SD( 1)),PDSA(12,P_D( 1)),PDSB(12,P_SD( 1)),PDSA(13,P_D( 1)),PDSB(13,P_SD( 1)),PDSA(14,P_D( 1)),PDSB(14,P_SD( 1)),PDSA(15,P_D( 1)),PDSB(15,P_SD( 1)));
    P("DQ2"  ,P_IN( ),P_     ,P_BCLK(  ),P_CCLK(  ),P_DRE( ),P_DRENRZ,P_DRECLK( ),P_IOC,P_OUTL( ),P_VT( ),P_DRCYCDLY(wl),P_EXPCYCDLY(rl),P_STRB( , ),P_EXPA(1), P_STRB( , ),P_EXPB(2),PDSA(1,P_D( 2)),PDSB(1,P_SD( 2)),PDSA(2,P_D( 2)),PDSB(2,P_SD( 2)),PDSA(3,P_D( 2)),PDSB(3,P_SD( 2)),PDSA(4,P_D( 2)),PDSB(4,P_SD( 2)),PDSA(5,P_D( 2)),PDSB(5,P_SD( 2)),PDSA(6,P_D( 2)),PDSB(6,P_SD( 2)),PDSA(7,P_D( 2)),PDSB(7,P_SD( 2)),PDSA(8,P_D( 2)),PDSB(8,P_SD( 2)),PDSA(9,P_D( 2)),PDSB(9,P_SD( 2)),PDSA(10,P_D( 2)),PDSB(10,P_SD( 2)),PDSA(11,P_D( 2)),PDSB(11,P_SD( 2)),PDSA(12,P_D( 2)),PDSB(12,P_SD( 2)),PDSA(13,P_D( 2)),PDSB(13,P_SD( 2)),PDSA(14,P_D( 2)),PDSB(14,P_SD( 2)),PDSA(15,P_D( 2)),PDSB(15,P_SD( 2)));
    P("DQ3"  ,P_IN( ),P_     ,P_BCLK(  ),P_CCLK(  ),P_DRE( ),P_DRENRZ,P_DRECLK( ),P_IOC,P_OUTL( ),P_VT( ),P_DRCYCDLY(wl),P_EXPCYCDLY(rl),P_STRB( , ),P_EXPA(1), P_STRB( , ),P_EXPB(2),PDSA(1,P_D( 3)),PDSB(1,P_SD( 3)),PDSA(2,P_D( 3)),PDSB(2,P_SD( 3)),PDSA(3,P_D( 3)),PDSB(3,P_SD( 3)),PDSA(4,P_D( 3)),PDSB(4,P_SD( 3)),PDSA(5,P_D( 3)),PDSB(5,P_SD( 3)),PDSA(6,P_D( 3)),PDSB(6,P_SD( 3)),PDSA(7,P_D( 3)),PDSB(7,P_SD( 3)),PDSA(8,P_D( 3)),PDSB(8,P_SD( 3)),PDSA(9,P_D( 3)),PDSB(9,P_SD( 3)),PDSA(10,P_D( 3)),PDSB(10,P_SD( 3)),PDSA(11,P_D( 3)),PDSB(11,P_SD( 3)),PDSA(12,P_D( 3)),PDSB(12,P_SD( 3)),PDSA(13,P_D( 3)),PDSB(13,P_SD( 3)),PDSA(14,P_D( 3)),PDSB(14,P_SD( 3)),PDSA(15,P_D( 3)),PDSB(15,P_SD( 3)));
    P("DQ4"  ,P_IN( ),P_     ,P_BCLK(  ),P_CCLK(  ),P_DRE( ),P_DRENRZ,P_DRECLK( ),P_IOC,P_OUTL( ),P_VT( ),P_DRCYCDLY(wl),P_EXPCYCDLY(rl),P_STRB( , ),P_EXPA(1), P_STRB( , ),P_EXPB(2),PDSA(1,P_D( 4)),PDSB(1,P_SD( 4)),PDSA(2,P_D( 4)),PDSB(2,P_SD( 4)),PDSA(3,P_D( 4)),PDSB(3,P_SD( 4)),PDSA(4,P_D( 4)),PDSB(4,P_SD( 4)),PDSA(5,P_D( 4)),PDSB(5,P_SD( 4)),PDSA(6,P_D( 4)),PDSB(6,P_SD( 4)),PDSA(7,P_D( 4)),PDSB(7,P_SD( 4)),PDSA(8,P_D( 4)),PDSB(8,P_SD( 4)),PDSA(9,P_D( 4)),PDSB(9,P_SD( 4)),PDSA(10,P_D( 4)),PDSB(10,P_SD( 4)),PDSA(11,P_D( 4)),PDSB(11,P_SD( 4)),PDSA(12,P_D( 4)),PDSB(12,P_SD( 4)),PDSA(13,P_D( 4)),PDSB(13,P_SD( 4)),PDSA(14,P_D( 4)),PDSB(14,P_SD( 4)),PDSA(15,P_D( 4)),PDSB(15,P_SD( 4)));
    P("DQ5"  ,P_IN( ),P_     ,P_BCLK(  ),P_CCLK(  ),P_DRE( ),P_DRENRZ,P_DRECLK( ),P_IOC,P_OUTL( ),P_VT( ),P_DRCYCDLY(wl),P_EXPCYCDLY(rl),P_STRB( , ),P_EXPA(1), P_STRB( , ),P_EXPB(2),PDSA(1,P_D( 5)),PDSB(1,P_SD( 5)),PDSA(2,P_D( 5)),PDSB(2,P_SD( 5)),PDSA(3,P_D( 5)),PDSB(3,P_SD( 5)),PDSA(4,P_D( 5)),PDSB(4,P_SD( 5)),PDSA(5,P_D( 5)),PDSB(5,P_SD( 5)),PDSA(6,P_D( 5)),PDSB(6,P_SD( 5)),PDSA(7,P_D( 5)),PDSB(7,P_SD( 5)),PDSA(8,P_D( 5)),PDSB(8,P_SD( 5)),PDSA(9,P_D( 5)),PDSB(9,P_SD( 5)),PDSA(10,P_D( 5)),PDSB(10,P_SD( 5)),PDSA(11,P_D( 5)),PDSB(11,P_SD( 5)),PDSA(12,P_D( 5)),PDSB(12,P_SD( 5)),PDSA(13,P_D( 5)),PDSB(13,P_SD( 5)),PDSA(14,P_D( 5)),PDSB(14,P_SD( 5)),PDSA(15,P_D( 5)),PDSB(15,P_SD( 5)));
    P("DQ6"  ,P_IN( ),P_     ,P_BCLK(  ),P_CCLK(  ),P_DRE( ),P_DRENRZ,P_DRECLK( ),P_IOC,P_OUTL( ),P_VT( ),P_DRCYCDLY(wl),P_EXPCYCDLY(rl),P_STRB( , ),P_EXPA(1), P_STRB( , ),P_EXPB(2),PDSA(1,P_D( 6)),PDSB(1,P_SD( 6)),PDSA(2,P_D( 6)),PDSB(2,P_SD( 6)),PDSA(3,P_D( 6)),PDSB(3,P_SD( 6)),PDSA(4,P_D( 6)),PDSB(4,P_SD( 6)),PDSA(5,P_D( 6)),PDSB(5,P_SD( 6)),PDSA(6,P_D( 6)),PDSB(6,P_SD( 6)),PDSA(7,P_D( 6)),PDSB(7,P_SD( 6)),PDSA(8,P_D( 6)),PDSB(8,P_SD( 6)),PDSA(9,P_D( 6)),PDSB(9,P_SD( 6)),PDSA(10,P_D( 6)),PDSB(10,P_SD( 6)),PDSA(11,P_D( 6)),PDSB(11,P_SD( 6)),PDSA(12,P_D( 6)),PDSB(12,P_SD( 6)),PDSA(13,P_D( 6)),PDSB(13,P_SD( 6)),PDSA(14,P_D( 6)),PDSB(14,P_SD( 6)),PDSA(15,P_D( 6)),PDSB(15,P_SD( 6)));
    P("DQ7"  ,P_IN( ),P_     ,P_BCLK(  ),P_CCLK(  ),P_DRE( ),P_DRENRZ,P_DRECLK( ),P_IOC,P_OUTL( ),P_VT( ),P_DRCYCDLY(wl),P_EXPCYCDLY(rl),P_STRB( , ),P_EXPA(1), P_STRB( , ),P_EXPB(2),PDSA(1,P_D( 7)),PDSB(1,P_SD( 7)),PDSA(2,P_D( 7)),PDSB(2,P_SD( 7)),PDSA(3,P_D( 7)),PDSB(3,P_SD( 7)),PDSA(4,P_D( 7)),PDSB(4,P_SD( 7)),PDSA(5,P_D( 7)),PDSB(5,P_SD( 7)),PDSA(6,P_D( 7)),PDSB(6,P_SD( 7)),PDSA(7,P_D( 7)),PDSB(7,P_SD( 7)),PDSA(8,P_D( 7)),PDSB(8,P_SD( 7)),PDSA(9,P_D( 7)),PDSB(9,P_SD( 7)),PDSA(10,P_D( 7)),PDSB(10,P_SD( 7)),PDSA(11,P_D( 7)),PDSB(11,P_SD( 7)),PDSA(12,P_D( 7)),PDSB(12,P_SD( 7)),PDSA(13,P_D( 7)),PDSB(13,P_SD( 7)),PDSA(14,P_D( 7)),PDSB(14,P_SD( 7)),PDSA(15,P_D( 7)),PDSB(15,P_SD( 7)));
    P("DQ8"  ,P_IN( ),P_     ,P_BCLK(  ),P_CCLK(  ),P_DRE( ),P_DRENRZ,P_DRECLK( ),P_IOC,P_OUTL( ),P_VT( ),P_DRCYCDLY(wl),P_EXPCYCDLY(rl),P_STRB( , ),P_EXPA(1), P_STRB( , ),P_EXPB(2),PDSA(1,P_D( 0)),PDSB(1,P_SD( 0)),PDSA(2,P_D( 0)),PDSB(2,P_SD( 0)),PDSA(3,P_D( 0)),PDSB(3,P_SD( 0)),PDSA(4,P_D( 0)),PDSB(4,P_SD( 0)),PDSA(5,P_D( 0)),PDSB(5,P_SD( 0)),PDSA(6,P_D( 0)),PDSB(6,P_SD( 0)),PDSA(7,P_D( 0)),PDSB(7,P_SD( 0)),PDSA(8,P_D( 0)),PDSB(8,P_SD( 0)),PDSA(9,P_D( 0)),PDSB(9,P_SD( 0)),PDSA(10,P_D( 0)),PDSB(10,P_SD( 0)),PDSA(11,P_D( 0)),PDSB(11,P_SD( 0)),PDSA(12,P_D( 0)),PDSB(12,P_SD( 0)),PDSA(13,P_D( 0)),PDSB(13,P_SD( 0)),PDSA(14,P_D( 0)),PDSB(14,P_SD( 0)),PDSA(15,P_D( 0)),PDSB(15,P_SD( 0)));
    P("DQ9"  ,P_IN( ),P_     ,P_BCLK(  ),P_CCLK(  ),P_DRE( ),P_DRENRZ,P_DRECLK( ),P_IOC,P_OUTL( ),P_VT( ),P_DRCYCDLY(wl),P_EXPCYCDLY(rl),P_STRB( , ),P_EXPA(1), P_STRB( , ),P_EXPB(2),PDSA(1,P_D( 1)),PDSB(1,P_SD( 1)),PDSA(2,P_D( 1)),PDSB(2,P_SD( 1)),PDSA(3,P_D( 1)),PDSB(3,P_SD( 1)),PDSA(4,P_D( 1)),PDSB(4,P_SD( 1)),PDSA(5,P_D( 1)),PDSB(5,P_SD( 1)),PDSA(6,P_D( 1)),PDSB(6,P_SD( 1)),PDSA(7,P_D( 1)),PDSB(7,P_SD( 1)),PDSA(8,P_D( 1)),PDSB(8,P_SD( 1)),PDSA(9,P_D( 1)),PDSB(9,P_SD( 1)),PDSA(10,P_D( 1)),PDSB(10,P_SD( 1)),PDSA(11,P_D( 1)),PDSB(11,P_SD( 1)),PDSA(12,P_D( 1)),PDSB(12,P_SD( 1)),PDSA(13,P_D( 1)),PDSB(13,P_SD( 1)),PDSA(14,P_D( 1)),PDSB(14,P_SD( 1)),PDSA(15,P_D( 1)),PDSB(15,P_SD( 1)));
    P("DQ10" ,P_IN( ),P_     ,P_BCLK(  ),P_CCLK(  ),P_DRE( ),P_DRENRZ,P_DRECLK( ),P_IOC,P_OUTL( ),P_VT( ),P_DRCYCDLY(wl),P_EXPCYCDLY(rl),P_STRB( , ),P_EXPA(1), P_STRB( , ),P_EXPB(2),PDSA(1,P_D( 2)),PDSB(1,P_SD( 2)),PDSA(2,P_D( 2)),PDSB(2,P_SD( 2)),PDSA(3,P_D( 2)),PDSB(3,P_SD( 2)),PDSA(4,P_D( 2)),PDSB(4,P_SD( 2)),PDSA(5,P_D( 2)),PDSB(5,P_SD( 2)),PDSA(6,P_D( 2)),PDSB(6,P_SD( 2)),PDSA(7,P_D( 2)),PDSB(7,P_SD( 2)),PDSA(8,P_D( 2)),PDSB(8,P_SD( 2)),PDSA(9,P_D( 2)),PDSB(9,P_SD( 2)),PDSA(10,P_D( 2)),PDSB(10,P_SD( 2)),PDSA(11,P_D( 2)),PDSB(11,P_SD( 2)),PDSA(12,P_D( 2)),PDSB(12,P_SD( 2)),PDSA(13,P_D( 2)),PDSB(13,P_SD( 2)),PDSA(14,P_D( 2)),PDSB(14,P_SD( 2)),PDSA(15,P_D( 2)),PDSB(15,P_SD( 2)));
    P("DQ11" ,P_IN( ),P_     ,P_BCLK(  ),P_CCLK(  ),P_DRE( ),P_DRENRZ,P_DRECLK( ),P_IOC,P_OUTL( ),P_VT( ),P_DRCYCDLY(wl),P_EXPCYCDLY(rl),P_STRB( , ),P_EXPA(1), P_STRB( , ),P_EXPB(2),PDSA(1,P_D( 3)),PDSB(1,P_SD( 3)),PDSA(2,P_D( 3)),PDSB(2,P_SD( 3)),PDSA(3,P_D( 3)),PDSB(3,P_SD( 3)),PDSA(4,P_D( 3)),PDSB(4,P_SD( 3)),PDSA(5,P_D( 3)),PDSB(5,P_SD( 3)),PDSA(6,P_D( 3)),PDSB(6,P_SD( 3)),PDSA(7,P_D( 3)),PDSB(7,P_SD( 3)),PDSA(8,P_D( 3)),PDSB(8,P_SD( 3)),PDSA(9,P_D( 3)),PDSB(9,P_SD( 3)),PDSA(10,P_D( 3)),PDSB(10,P_SD( 3)),PDSA(11,P_D( 3)),PDSB(11,P_SD( 3)),PDSA(12,P_D( 3)),PDSB(12,P_SD( 3)),PDSA(13,P_D( 3)),PDSB(13,P_SD( 3)),PDSA(14,P_D( 3)),PDSB(14,P_SD( 3)),PDSA(15,P_D( 3)),PDSB(15,P_SD( 3)));
    P("DQ12" ,P_IN( ),P_     ,P_BCLK(  ),P_CCLK(  ),P_DRE( ),P_DRENRZ,P_DRECLK( ),P_IOC,P_OUTL( ),P_VT( ),P_DRCYCDLY(wl),P_EXPCYCDLY(rl),P_STRB( , ),P_EXPA(1), P_STRB( , ),P_EXPB(2),PDSA(1,P_D( 4)),PDSB(1,P_SD( 4)),PDSA(2,P_D( 4)),PDSB(2,P_SD( 4)),PDSA(3,P_D( 4)),PDSB(3,P_SD( 4)),PDSA(4,P_D( 4)),PDSB(4,P_SD( 4)),PDSA(5,P_D( 4)),PDSB(5,P_SD( 4)),PDSA(6,P_D( 4)),PDSB(6,P_SD( 4)),PDSA(7,P_D( 4)),PDSB(7,P_SD( 4)),PDSA(8,P_D( 4)),PDSB(8,P_SD( 4)),PDSA(9,P_D( 4)),PDSB(9,P_SD( 4)),PDSA(10,P_D( 4)),PDSB(10,P_SD( 4)),PDSA(11,P_D( 4)),PDSB(11,P_SD( 4)),PDSA(12,P_D( 4)),PDSB(12,P_SD( 4)),PDSA(13,P_D( 4)),PDSB(13,P_SD( 4)),PDSA(14,P_D( 4)),PDSB(14,P_SD( 4)),PDSA(15,P_D( 4)),PDSB(15,P_SD( 4)));
    P("DQ13" ,P_IN( ),P_     ,P_BCLK(  ),P_CCLK(  ),P_DRE( ),P_DRENRZ,P_DRECLK( ),P_IOC,P_OUTL( ),P_VT( ),P_DRCYCDLY(wl),P_EXPCYCDLY(rl),P_STRB( , ),P_EXPA(1), P_STRB( , ),P_EXPB(2),PDSA(1,P_D( 5)),PDSB(1,P_SD( 5)),PDSA(2,P_D( 5)),PDSB(2,P_SD( 5)),PDSA(3,P_D( 5)),PDSB(3,P_SD( 5)),PDSA(4,P_D( 5)),PDSB(4,P_SD( 5)),PDSA(5,P_D( 5)),PDSB(5,P_SD( 5)),PDSA(6,P_D( 5)),PDSB(6,P_SD( 5)),PDSA(7,P_D( 5)),PDSB(7,P_SD( 5)),PDSA(8,P_D( 5)),PDSB(8,P_SD( 5)),PDSA(9,P_D( 5)),PDSB(9,P_SD( 5)),PDSA(10,P_D( 5)),PDSB(10,P_SD( 5)),PDSA(11,P_D( 5)),PDSB(11,P_SD( 5)),PDSA(12,P_D( 5)),PDSB(12,P_SD( 5)),PDSA(13,P_D( 5)),PDSB(13,P_SD( 5)),PDSA(14,P_D( 5)),PDSB(14,P_SD( 5)),PDSA(15,P_D( 5)),PDSB(15,P_SD( 5)));
    P("DQ14" ,P_IN( ),P_     ,P_BCLK(  ),P_CCLK(  ),P_DRE( ),P_DRENRZ,P_DRECLK( ),P_IOC,P_OUTL( ),P_VT( ),P_DRCYCDLY(wl),P_EXPCYCDLY(rl),P_STRB( , ),P_EXPA(1), P_STRB( , ),P_EXPB(2),PDSA(1,P_D( 6)),PDSB(1,P_SD( 6)),PDSA(2,P_D( 6)),PDSB(2,P_SD( 6)),PDSA(3,P_D( 6)),PDSB(3,P_SD( 6)),PDSA(4,P_D( 6)),PDSB(4,P_SD( 6)),PDSA(5,P_D( 6)),PDSB(5,P_SD( 6)),PDSA(6,P_D( 6)),PDSB(6,P_SD( 6)),PDSA(7,P_D( 6)),PDSB(7,P_SD( 6)),PDSA(8,P_D( 6)),PDSB(8,P_SD( 6)),PDSA(9,P_D( 6)),PDSB(9,P_SD( 6)),PDSA(10,P_D( 6)),PDSB(10,P_SD( 6)),PDSA(11,P_D( 6)),PDSB(11,P_SD( 6)),PDSA(12,P_D( 6)),PDSB(12,P_SD( 6)),PDSA(13,P_D( 6)),PDSB(13,P_SD( 6)),PDSA(14,P_D( 6)),PDSB(14,P_SD( 6)),PDSA(15,P_D( 6)),PDSB(15,P_SD( 6)));
    P("DQ15" ,P_IN( ),P_     ,P_BCLK(  ),P_CCLK(  ),P_DRE( ),P_DRENRZ,P_DRECLK( ),P_IOC,P_OUTL( ),P_VT( ),P_DRCYCDLY(wl),P_EXPCYCDLY(rl),P_STRB( , ),P_EXPA(1), P_STRB( , ),P_EXPB(2),PDSA(1,P_D( 7)),PDSB(1,P_SD( 7)),PDSA(2,P_D( 7)),PDSB(2,P_SD( 7)),PDSA(3,P_D( 7)),PDSB(3,P_SD( 7)),PDSA(4,P_D( 7)),PDSB(4,P_SD( 7)),PDSA(5,P_D( 7)),PDSB(5,P_SD( 7)),PDSA(6,P_D( 7)),PDSB(6,P_SD( 7)),PDSA(7,P_D( 7)),PDSB(7,P_SD( 7)),PDSA(8,P_D( 7)),PDSB(8,P_SD( 7)),PDSA(9,P_D( 7)),PDSB(9,P_SD( 7)),PDSA(10,P_D( 7)),PDSB(10,P_SD( 7)),PDSA(11,P_D( 7)),PDSB(11,P_SD( 7)),PDSA(12,P_D( 7)),PDSB(12,P_SD( 7)),PDSA(13,P_D( 7)),PDSB(13,P_SD( 7)),PDSA(14,P_D( 7)),PDSB(14,P_SD( 7)),PDSA(15,P_D( 7)),PDSB(15,P_SD( 7)));
    P("DMI"  ,P_IN( ),P_     ,P_BCLK(  ),P_CCLK(  ),P_DRE( ),P_DRENRZ,P_DRECLK( ),P_IOC,P_OUTL( ),P_VT( ),P_DRCYCDLY(wl),P_EXPCYCDLY(rl),P_STRB( , ),P_EXPA(1), P_STRB( , ),P_EXPB(2),PDSA(1,P_C(23)),PDSB(1,P_C(24)) ,PDSA(2,P_C(23)),PDSB(2,P_C(24)) ,PDSA(3,P_C(23)),PDSB(3,P_C(24)) ,PDSA(4,P_C(23)),PDSB(4,P_C(24)) ,PDSA(5,P_C(23)),PDSB(5,P_C(24)) ,PDSA(6,P_C(23)),PDSB(6,P_C(24)) ,PDSA(7,P_C(23)),PDSB(7,P_C(24)) ,PDSA(8,P_C(23)),PDSB(8,P_C(24)) ,PDSA(9,P_C(23)),PDSB(9,P_C(24)) ,PDSA(10,P_C(23)),PDSB(10,P_C(24)) ,PDSA(11,P_C(23)),PDSB(11,P_C(24)) ,PDSA(12,P_C(23)),PDSB(12,P_C(24)) ,PDSA(13,P_C(23)),PDSB(13,P_C(24)) ,PDSA(14,P_C(23)),PDSB(14,P_C(24)) ,PDSA(15,P_C(23)),PDSB(15,P_C(24)) );
    P("DQS_t",P_IN( ),P_     ,P_BCLK(  ),P_CCLK(  ),P_DRE( ),P_DRENRZ,P_DRECLK( ),P_IOC,P_OUTL( ),P_VT( ),P_DRCYCDLY(wl),P_EXPCYCDLY(rl),P_STRB( , ),P_EXPA(3), P_STRB( , ),P_EXPB(4),PDSA(1,P_C(22)),PDSB(1,P_FL)    ,PDSA(2,P_C(22)),PDSB(2,P_FL)    ,PDSA(3,P_C(22)),PDSB(3,P_FL)    ,PDSA(4,P_C(22)),PDSB(4,P_FL)    ,PDSA(5,P_C(22)),PDSB(5,P_FL)    ,PDSA(6,P_C(22)),PDSB(6,P_FL)    ,PDSA(7,P_C(22)),PDSB(7,P_FL)    ,PDSA(8,P_C(22)),PDSB(8,P_FL)    ,PDSA(9,P_C(22)),PDSB(9,P_FL)    ,PDSA(10,P_C(22)),PDSB(10,P_FL)    ,PDSA(11,P_C(22)),PDSB(11,P_FL)    ,PDSA(12,P_C(22)),PDSB(12,P_FL)    ,PDSA(13,P_C(22)),PDSB(13,P_FL)    ,PDSA(14,P_C(22)),PDSB(14,P_FL)    ,PDSA(15,P_C(22)),PDSB(15,P_FL)    );        
    P("DQS_c",P_IN( ),P_     ,P_BCLK(  ),P_CCLK(  ),P_DRE( ),P_DRENRZ,P_DRECLK( ),P_IOC,P_OUTL( ),P_VT( ),P_DRCYCDLY(wl),P_EXPCYCDLY(rl),P_STRB( , ),P_EXPA(3), P_STRB( , ),P_EXPB(4),PDSA(1,P_I_C(22)),PDSB(1,P_FH)  ,PDSA(2,P_I_C(22)),PDSB(2,P_FH)  ,PDSA(3,P_I_C(22)),PDSB(3,P_FH)  ,PDSA(4,P_I_C(22)),PDSB(4,P_FH)  ,PDSA(5,P_I_C(22)),PDSB(5,P_FH)  ,PDSA(6,P_I_C(22)),PDSB(6,P_FH)  ,PDSA(7,P_I_C(22)),PDSB(7,P_FH)  ,PDSA(8,P_I_C(22)),PDSB(8,P_FH)  ,PDSA(9,P_I_C(22)),PDSB(9,P_FH)  ,PDSA(10,P_I_C(22)),PDSB(10,P_FH)  ,PDSA(11,P_I_C(22)),PDSB(11,P_FH)  ,PDSA(12,P_I_C(22)),PDSB(12,P_FH)  ,PDSA(13,P_I_C(22)),PDSB(13,P_FH)  ,PDSA(14,P_I_C(22)),PDSB(14,P_FH)  ,PDSA(15,P_I_C(22)),PDSB(15,P_FH)  );
               
*/
}


