// ################################################################################
// # NOTICE: THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,      #
// # EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF           #
// # MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.       #
// # IN NO EVENT SHALL ADVANTEST BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER        #
// # LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING      #
// # FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER          #
// # DEALINGS IN THE SOFTWARE.                                                    #
// ################################################################################
#ifndef ___reg_H
#define ___reg_H
#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

#include "Reg.h"

#define PC(r1)             (UTL_SetRegUs( handle, UT_REG_STAPC, 1, r1))  
#define BAR1(r1)           (UTL_SetRegUs( handle, UT_REG_BAR1 , 1, r1))  
#define JAR(r1)            (UTL_SetRegUs( handle, UT_REG_JAR  , 1, r1))  
#define DRE1(r1)           (UTL_SetRegRb( handle, UT_REG_DRE1 ,    r1))  
#define DRE2(r1)           (UTL_SetRegRb( handle, UT_REG_DRE2 ,    r1))  
#define CPE1(r1)           (UTL_SetRegRb( handle, UT_REG_CPE1 ,    r1))  
#define CPE2(r1)           (UTL_SetRegRb( handle, UT_REG_CPE2 ,    r1))  
#define CPE3(r1)           (UTL_SetRegRb( handle, UT_REG_CPE3 ,    r1))  
#define CPE4(r1)           (UTL_SetRegRb( handle, UT_REG_CPE4 ,    r1))  
#define IDX1(r1)           (UTL_SetRegUs( handle, UT_REG_IDX1 , 1, r1))  
#define IDX2(r1)           (UTL_SetRegUs( handle, UT_REG_IDX2 , 1, r1))  
#define IDX3(r1)           (UTL_SetRegUs( handle, UT_REG_IDX3 , 1, r1))  
#define IDX4(r1)           (UTL_SetRegUs( handle, UT_REG_IDX4 , 1, r1))  
#define IDX5(r1)           (UTL_SetRegUs( handle, UT_REG_IDX5 , 1, r1))  
#define IDX6(r1)           (UTL_SetRegUs( handle, UT_REG_IDX6 , 1, r1))  
#define IDX7(r1)           (UTL_SetRegUs( handle, UT_REG_IDX7 , 1, r1))  
#define IDX8(r1)           (UTL_SetRegUs( handle, UT_REG_IDX8 , 1, r1))  
#define IDX9(r1)           (UTL_SetRegUs( handle, UT_REG_IDX9 , 1, r1))  
#define IDX10(r1)          (UTL_SetRegUs( handle, UT_REG_IDX10, 1, r1))  
#define IDX11(r1)          (UTL_SetRegUs( handle, UT_REG_IDX11, 1, r1))  
#define IDX12(r1)          (UTL_SetRegUs( handle, UT_REG_IDX12, 1, r1))  
#define IDX13(r1)          (UTL_SetRegUs( handle, UT_REG_IDX13, 1, r1))  
#define IDX14(r1)          (UTL_SetRegUs( handle, UT_REG_IDX14, 1, r1))  
#define IDX15(r1)          (UTL_SetRegUs( handle, UT_REG_IDX15, 1, r1))  
#define IDX16(r1)          (UTL_SetRegUs( handle, UT_REG_IDX16, 1, r1))  
#define LMAX(r1)           (UTL_SetRegUs( handle, UT_REG_LMAX , 1, r1))  
#define HMAX(r1)           (UTL_SetRegUs( handle, UT_REG_HMAX , 1, r1))  
#define XMAX(r1)           (UTL_SetRegUs( handle, UT_REG_XMAX , 1, r1))  
#define YMAX(r1)           (UTL_SetRegUs( handle, UT_REG_YMAX , 1, r1))  
#define ZMAX(r1)           (UTL_SetRegUs( handle, UT_REG_ZMAX , 1, r1))  
#define XH(r1)             (UTL_SetRegUs( handle, UT_REG_XH   , 1, r1))   
#define YH(r1)             (UTL_SetRegUs( handle, UT_REG_YH   , 1, r1))   
#define ZZ(r1)             (UTL_SetRegUs( handle, UT_REG_ZH   , 1, r1))   
#define R_D1(r1)             (UTL_SetRegUs( handle, UT_REG_D1   , 1, r1))   
#define D1A(r1)            (UTL_SetRegUs( handle, UT_REG_D1   , 1, r1))   
#define D1B(r1)            (UTL_SetRegUs( handle, UT_REG_D1B  , 1, r1))   
#define D1C(r1)            (UTL_SetRegUs( handle, UT_REG_D1C  , 1, r1))   
#define D1D(r1)            (UTL_SetRegUs( handle, UT_REG_D1D  , 1, r1))   
#define D1E(r1)            (UTL_SetRegUs( handle, UT_REG_D1E  , 1, r1))   
#define D1F(r1)            (UTL_SetRegUs( handle, UT_REG_D1F  , 1, r1))   
#define D1G(r1)            (UTL_SetRegUs( handle, UT_REG_D1G  , 1, r1))   
#define D1H(r1)            (UTL_SetRegUs( handle, UT_REG_D1H  , 1, r1))   
//#define D2(r1)             (UTL_SetRegUs( handle, UT_REG_D2   , 1, r1))   
#define D2A(r1)            (UTL_SetRegUs( handle, UT_REG_D2   , 1, r1))   
#define D2B(r1)            (UTL_SetRegUs( handle, UT_REG_D2B  , 1, r1))   
#define D2C(r1)            (UTL_SetRegUs( handle, UT_REG_D2C  , 1, r1))   
#define D2D(r1)            (UTL_SetRegUs( handle, UT_REG_D2D  , 1, r1))   
#define D2E(r1)            (UTL_SetRegUs( handle, UT_REG_D2E  , 1, r1))   
#define D2F(r1)            (UTL_SetRegUs( handle, UT_REG_D2F  , 1, r1))   
#define D2G(r1)            (UTL_SetRegUs( handle, UT_REG_D2G  , 1, r1))   
#define D2H(r1)            (UTL_SetRegUs( handle, UT_REG_D2H  , 1, r1))   
#define D3B(r1)            (UTL_SetRegUs( handle, UT_REG_D3B  , 1, r1))   
#define D4B(r1)            (UTL_SetRegUs( handle, UT_REG_D4B  , 1, r1))   

#define BH(r1)             (UTL_SetRegUs( handle, UT_REG_BH   , 1, r1))   
#define BD1(r1)            (UTL_SetRegUs( handle, UT_REG_BD   , 1, r1))   
#define BD2(r1)            (UTL_SetRegUs( handle, UT_REG_BD2  , 1, r1))   
#define BD3(r1)            (UTL_SetRegUs( handle, UT_REG_BD3  , 1, r1))   
#define BD4(r1)            (UTL_SetRegUs( handle, UT_REG_BD4  , 1, r1))   
#define BD5(r1)            (UTL_SetRegUs( handle, UT_REG_BD5  , 1, r1))   
#define BD6(r1)            (UTL_SetRegUs( handle, UT_REG_BD6  , 1, r1))   
#define BD7(r1)            (UTL_SetRegUs( handle, UT_REG_BD7  , 1, r1))   
#define NH(r1)             (UTL_SetRegUs( handle, UT_REG_NH   , 1, r1))   
#define ND1(r1)            (UTL_SetRegUs( handle, UT_REG_ND   , 1, r1))   
#define ND2(r1)            (UTL_SetRegUs( handle, UT_REG_ND2  , 1, r1))   
#define ND3(r1)            (UTL_SetRegUs( handle, UT_REG_ND3  , 1, r1))   
#define ND4(r1)            (UTL_SetRegUs( handle, UT_REG_ND4  , 1, r1))   
#define ND5(r1)            (UTL_SetRegUs( handle, UT_REG_ND5  , 1, r1))   
#define ND6(r1)            (UTL_SetRegUs( handle, UT_REG_ND6  , 1, r1))   
#define ND7(r1)            (UTL_SetRegUs( handle, UT_REG_ND7  , 1, r1))   

#define BH_2(r1)           (UTL_SetRegUs( handle, UT_REG_BH_2   , 1, r1))   
#define BD1_2(r1)          (UTL_SetRegUs( handle, UT_REG_BD_2   , 1, r1))   
#define BD2_2(r1)          (UTL_SetRegUs( handle, UT_REG_BD2_2  , 1, r1))   
#define BD3_2(r1)          (UTL_SetRegUs( handle, UT_REG_BD3_2  , 1, r1))   
#define BD4_2(r1)          (UTL_SetRegUs( handle, UT_REG_BD4_2  , 1, r1))   
#define BD5_2(r1)          (UTL_SetRegUs( handle, UT_REG_BD5_2  , 1, r1))   
#define BD6_2(r1)          (UTL_SetRegUs( handle, UT_REG_BD6_2  , 1, r1))   
#define BD7_2(r1)          (UTL_SetRegUs( handle, UT_REG_BD7_2  , 1, r1))   
#define NH_2(r1)           (UTL_SetRegUs( handle, UT_REG_NH_2   , 1, r1))   
#define ND1_2(r1)          (UTL_SetRegUs( handle, UT_REG_ND_2   , 1, r1))   
#define ND2_2(r1)          (UTL_SetRegUs( handle, UT_REG_ND2_2  , 1, r1))   
#define ND3_2(r1)          (UTL_SetRegUs( handle, UT_REG_ND3_2  , 1, r1))   
#define ND4_2(r1)          (UTL_SetRegUs( handle, UT_REG_ND4_2  , 1, r1))   
#define ND5_2(r1)          (UTL_SetRegUs( handle, UT_REG_ND5_2  , 1, r1))   
#define ND6_2(r1)          (UTL_SetRegUs( handle, UT_REG_ND6_2  , 1, r1))   
#define ND7_2(r1)          (UTL_SetRegUs( handle, UT_REG_ND7_2  , 1, r1))   

#define R_D2(r1)             (UTL_SetRegUs( handle, UT_REG_D2   , 1, r1))   
#define R_D3(r1)             (UTL_SetRegUs( handle, UT_REG_D3   , 1, r1))   
#define R_D4(r1)             (UTL_SetRegUs( handle, UT_REG_D4   , 1, r1))   

#define D5_1(r1)           (UTL_SetRegUs( handle, UT_REG_D5   , 1, r1))   
#define D5_2(r1)           (UTL_SetRegUs( handle, UT_REG_D5_2 , 1, r1))   
#define D6_1(r1)           (UTL_SetRegUs( handle, UT_REG_D6   , 1, r1))   
#define D6_2(r1)           (UTL_SetRegUs( handle, UT_REG_D6_2 , 1, r1))   

#define DSD(r1)            (UTL_SetRegUs( handle, UT_REG_DSD  , 1, r1))  
#define XOS(r1)            (UTL_SetRegUs( handle, UT_REG_XOS  , 1, r1))  
#define YOS(r1)            (UTL_SetRegUs( handle, UT_REG_YOS  , 1, r1))  
#define XCMR(r1)           (UTL_SetRegUs( handle, UT_REG_XCMR , 1, r1))  
#define XCMR1(r1)          (UTL_SetRegUs( handle, UT_REG_XCMR , 1, r1))  
#define XCMR2(r1)          (UTL_SetRegUs( handle, UT_REG_XCMR2, 1, r1))  
#define XCMR3(r1)          (UTL_SetRegUs( handle, UT_REG_XCMR3, 1, r1))  
#define XCMR4(r1)          (UTL_SetRegUs( handle, UT_REG_XCMR4, 1, r1))  
#define YCMR(r1)           (UTL_SetRegUs( handle, UT_REG_YCMR , 1, r1))  
#define YCMR1(r1)          (UTL_SetRegUs( handle, UT_REG_YCMR , 1, r1))  
#define YCMR2(r1)          (UTL_SetRegUs( handle, UT_REG_YCMR2, 1, r1))  
#define YCMR3(r1)          (UTL_SetRegUs( handle, UT_REG_YCMR3, 1, r1))  
#define YCMR4(r1)          (UTL_SetRegUs( handle, UT_REG_YCMR4, 1, r1))  
#define DINVD(r1)          (UTL_SetRegUs( handle, UT_REG_DINVD, 1, r1))  
#define DCMR1(r1)          (UTL_SetRegUs( handle, UT_REG_DCMR1, 1, r1))  
#define DCMR2(r1)          (UTL_SetRegUs( handle, UT_REG_DCMR2, 1, r1))  
#define XT2(r1)            (UTL_SetRegUs( handle, UT_REG_XT2   , 1, r1))   
#define XT3(r1)            (UTL_SetRegUs( handle, UT_REG_XT3   , 1, r1))   
#define XT4(r1)            (UTL_SetRegUs( handle, UT_REG_XT4   , 1, r1))   
#define XT5(r1)            (UTL_SetRegUs( handle, UT_REG_XT5   , 1, r1))   
#define XT6(r1)            (UTL_SetRegUs( handle, UT_REG_XT6   , 1, r1))   
#define XT7(r1)            (UTL_SetRegUs( handle, UT_REG_XT7   , 1, r1))   
#define XT8(r1)            (UTL_SetRegUs( handle, UT_REG_XT8   , 1, r1))   
#define XT9(r1)            (UTL_SetRegUs( handle, UT_REG_XT9   , 1, r1))   
#define XT10(r1)           (UTL_SetRegUs( handle, UT_REG_XT10  , 1, r1))   
#define XT11(r1)           (UTL_SetRegUs( handle, UT_REG_XT11  , 1, r1))   
#define XT12(r1)           (UTL_SetRegUs( handle, UT_REG_XT12  , 1, r1))   
#define XT13(r1)           (UTL_SetRegUs( handle, UT_REG_XT13  , 1, r1))   
#define XT14(r1)           (UTL_SetRegUs( handle, UT_REG_XT14  , 1, r1))   
#define XT15(r1)           (UTL_SetRegUs( handle, UT_REG_XT15  , 1, r1))   
#define YT2(r1)            (UTL_SetRegUs( handle, UT_REG_YT2   , 1, r1))   
#define YT3(r1)            (UTL_SetRegUs( handle, UT_REG_YT3   , 1, r1))   
#define YT4(r1)            (UTL_SetRegUs( handle, UT_REG_YT4   , 1, r1))   
#define YT5(r1)            (UTL_SetRegUs( handle, UT_REG_YT5   , 1, r1))   
#define YT6(r1)            (UTL_SetRegUs( handle, UT_REG_YT6   , 1, r1))   
#define YT7(r1)            (UTL_SetRegUs( handle, UT_REG_YT7   , 1, r1))   
#define YT8(r1)            (UTL_SetRegUs( handle, UT_REG_YT8   , 1, r1))   
#define YT9(r1)            (UTL_SetRegUs( handle, UT_REG_YT9   , 1, r1))   
#define YT10(r1)           (UTL_SetRegUs( handle, UT_REG_YT10  , 1, r1))   
#define YT11(r1)           (UTL_SetRegUs( handle, UT_REG_YT11  , 1, r1))   
#define YT12(r1)           (UTL_SetRegUs( handle, UT_REG_YT12  , 1, r1))   
#define YT13(r1)           (UTL_SetRegUs( handle, UT_REG_YT13  , 1, r1))   
#define YT14(r1)           (UTL_SetRegUs( handle, UT_REG_YT14  , 1, r1))   
#define YT15(r1)           (UTL_SetRegUs( handle, UT_REG_YT15  , 1, r1))   

#define TPH(r1)            (UTL_SetRegUs( handle, UT_REG_TPH  , 1, r1)) 
#define TPH1(r1)           (UTL_SetRegUs( handle, UT_REG_TPH  , 1, r1)) 
#define TPH2(r1)           (UTL_SetRegUs( handle, UT_REG_TPH2 , 1, r1)) 
#define TPH1_1(r1)         TPH1(r1)
#define TPH2_1(r1)         TPH2(r1)
#define TPH1_2(r1)         (UTL_SetRegUs( handle, UT_REG_TPH_2 , 1, r1)) 
#define TPH2_2(r1)         (UTL_SetRegUs( handle, UT_REG_TPH2_2, 1, r1)) 
#define DCMR(r1)           (UTL_SetRegUs( handle, UT_REG_DCMR  , 1, r1)) 
#define CD(r1)             (UTL_SetRegUs( handle, UT_REG_CD     , 1, r1)) 
#define REFRESH_CNT(r1)    (UTL_SetRegTimerCycleCnt( handle, UT_REG_REFRESH, UT_REG_TIMER_RANGE_CR1, r1)) 
#define REFRESH(r1)        (UTL_SetRegTimerTime    ( handle, UT_REG_REFRESH, r1)) 
#define PAUSE(r1)          (UTL_SetRegTimerTime    ( handle, UT_REG_PAUSE  , r1)) 
#define JET(r1)            (UTL_SetRegTimerTime    ( handle, UT_REG_JET    , r1)) 


#ifdef __cplusplus
}
#endif // __cplusplus
#endif // ___reg_H
